### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by sszemeresky** [dorny/test-reporter#366] opened 2024-01-25 13:41 UTC
## Describe
using test-reporter@1.7.0 throws a warning
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dorny/test-reporter@v1.7.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
## Proposed solution
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
## Alternatives considered
n/a

**Comment by jozefizso** [comment] 2024-01-25 13:46
Duplicate of https://github.com/dorny/test-reporter/issues/365 and https://github.com/dorny/test-reporter/pull/315

**Closed by jozefizso** 2024-01-25 13:46 UTC
Labels: enhancement
