### ISSUE TITLE
Report panel includes scroll bar

### ISSUE THREAD

**Issue by garysmith-img** [dorny/test-reporter#119] opened 2021-05-27 10:08 UTC
I'm not sure if this is something under your control but I've found that my generated report always shows a horizontal scroll bar. As a result I can't see the complete set of columns off to the right even though there appears to be enough available space.

![image](https://user-images.githubusercontent.com/82086803/119808458-0ae82280-bedc-11eb-981f-a16bd797ab96.png)

I think I've found the style that causes this. If I disable this in the chrome debugger then the scroll bar vanishes and the whole report displays nicely. 

![image](https://user-images.githubusercontent.com/82086803/119807757-5fd76900-bedb-11eb-83b3-e6b7af1d38f8.png)

The first column that shows the xml test call file is already wrapping so I wondered if there was a way to avoid the horizontal scroll bar?

**Comment by dorny** [comment] 2021-06-07 13:11
Hello,

I'm aware of this issue, the width of the table is ridiculously small. Unfortunately, I can't change it.
The report is generated as markdown text and GitHub is fully in charge of rendering and styling.
It's not possible to display your own HTML page or apply styling without going outside of GitHub.

Duplicate of #59

**Closed by dorny** 2021-06-07 13:11 UTC
